swagger: '2.0'

info:
  version: "0.0.1"
  title: Catalog Service API

paths:
  
          
  /products:
    get:
      tags:
        - product
      description: |
        Get all products (Max. 20 per query)
      produces:
        - application/json
      responses:
        200:
          description: Successful response
    post:
      tags:
        - product
      description: |
        Create a new product.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: product
          in: body
          description: a new product which needs to be created
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        201:
          description: Successful response
        400:
          description: Invaild input
          
  /products/{productId}:
    get:
      tags:
        - product
      description: |
        Get a product
      parameters:
        - in: path
          name: productId
          description: product id
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
        404:
          description: product can't be found
    put:
      description: |
        Update a product.
      parameters:
        - name: productId
          in: path
          description: productId
          required: true
          type: number
          format: int64
      responses:
        200:
          description: Successful response
        404:
          description: product can't be found
    delete:
      tags:
        - product
      description: "Deletes a product"
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: product id to delete
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
        404:
          description: product can't be found
  
  /products/{productId}/variations:
    get:
      tags:
        - variation
      description: |
        Get a varition
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    post:
      tags:
        - variation
      description: |
        Create a new variation.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: variation 
          in: body
          description: Variation object which needs to be added to the product
          required: true
          schema:
            $ref: "#/definitions/Variation"
      responses:
        200:
          description: Successful response
        400:
          description: Bad request
          
  /products/{productId}/variations/{variation_id}:
    put:
      tags:
        - variation
      description: |
        update variation object
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: variation_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    delete:
      tags:
        - variation
      description: |
        delete variation object
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: variation_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
          
definitions:
  Product:
    properties:
      id:
        type: integer
        format: int64
      type_id:  
        type: integer
        format: int64
      name:
        type: string
      content:
        type: string
      tags:
        type: string
      vendor:
        type: string
      list_price:
        type: number
      list_price_with_tax:
        type: number
      list_price_without_tax:
        type: number
      price:
        type: number
      price_with_tax:
        type: number
      price_without_tax:
        type: number
      weight:
        type: number
      sort_order:
        type: integer
      is_purchaseable:
        type: boolean
      is_backorderable:
        type: boolean
      is_preorderable:
        type: boolean
      is_shipping_address_required:
        type: boolean
      variations:
        type: integer
      permalink:
        type: integer
      page_title:
        type: integer
      meta_description:
        type: integer
      images:
        type: integer

  Variation:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      sku:
        type: string
      list_price:
        type: number
      list_price_with_tax:
        type: number
      list_price_without_tax:
        type: number
      price:
        type: number
      price_with_tax:
        type: number
      price_without_tax:
        type: number
      is_shipping_address_required:
        type: boolean
      weight:
        type: number
      sort_order:
        type: integer
      is_backorderable:
        type: boolean
      is_preorderable:
        type: boolean
      images:
        type: integer