swagger: '2.0'

info:
  version: "0.0.1"
  title: Inventory Service API

paths:


  /stock-items:
    get:
      tags:
        - stock-item
      description: |
        Get `stock-items` objects.
      produces:
        - application/json
      responses:
        200:
          description: Successful response
    post:
      tags:
        - stock-item
      description: |
        Create a `stock-items` object.
      produces:
        - application/json
      responses:
        201:
          description: Successful response


          
  /stock-items/cancel:
    post:
      tags:
        - stock-item
      description: |
        To cancel `stock-items` objects
      produces:
        - application/json
      responses:
        201:
          description: Successful response
          
  /stock-items/void:
    post:
      tags:
        - stock-item
      description: |
        To void an `stock-items` objects
      produces:
        - application/json
      responses:
        200:
          description: Successful response

          
  /stock-items/{stock-items-id}/void:
    post:
      tags:
        - stock-item
      description: |
        To void an `stock-items` object
      produces:
        - application/json
      parameters:
        - name: stock-items-id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /stock-items/{stock-items-id}/cancel:
    post:
      tags:
        - stock-item
      description: |
        To cancel an `stock-items` object
      produces:
        - application/json
      parameters:
        - name: stock-items-id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          

  /stock-movements:
    get:
      tags:
        - stock-movement
      description: |
        Get `stock-movement` objects.
      produces:
        - application/json
      responses:
        200:
          description: Successful response
    post:
      tags:
        - stock-movement
      description: |
        Create a `stock-movement` object.
      produces:
        - application/json
      responses:
        201:
          description: Successful response


  /stock-movements/{stock-movement-id}:
    get:
      tags:
        - stock-movement
      description: |
        Get `stock-movement` objects.
      produces:
        - application/json
      parameters:
        - name: stock-movement-id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response


 
    
definitions:
  Stock-item:
    properties:
      id:
        type: integer
        format: int64
      state:
        type: string
      order-id:
        type: integer
        format: int64
      product-id:
        type: integer
        format: int64
      variation-id:
        type: integer
        format: int64
  Stock-movement:
    properties:
      id:
        type: integer
        format: int64
      action:
        type: string
      quantity:
        type: integer
        format: int64
