swagger: '2.0'

info:
  version: "0.0.1"
  title: Inventory Service API

paths:

  /warehouses:
    get:
      tags:
        - warehouse
      description: |
        Get `Warehouse` objects.
      produces:
        - application/json
      responses:
        200:
          description: Successful response
    post:
      tags:
        - warehouse
      description: |
        Create a `Warehouse` object.
      produces:
        - application/json
      responses:
        201:
          description: Successful response
          
  /warehouses/stock-items:
    get:
      tags:
        - warehouse
      description: |
        Get `stock item` objects across all warehouse.
      produces:
        - application/json
      responses:
        200:
          description: Successful response
    post:
      tags:
        - warehouse
      description: |
        Create a `Warehouse` object.
      produces:
        - application/json
      responses:
        201:
          description: Successful response          
          
  /warehouse/{warehouseId}/stock-items:
    get:
      tags:
        - warehouse
      description: |
        Gets `stock_item` objects.
      produces:
        - application/json
      parameters:
        - name: warehouseId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
 
    
definitions:
  Store:
    properties:
      id:
        type: integer
        format: int64
  Product:
    properties:
      id:
        type: integer
        format: int64
  Variation:
    properties:
      id:
        type: integer
        format: int64
