swagger: '2.0'

info:
  version: "0.0.1"
  title: Order Service API

paths:

  /orders:
    get:
      description: |
        Get all orders
      produces:
        - application/json
      responses:
        200:
          description: Successful response

    post:
      tags: 
        - order
      description: |
        Create a new order.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Successful response
        400:
          description: Bad request
  
  /orders/{orderId}:
    get:
      tags:
        - order
      description: |
        Gets order object.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    put:
      tags:
        - order
      description: |
        Update existing order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          

  /orders/{orderId}/cancel:
    post:
      tags:
        - order
      description: |
        Cancel the order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/line_items:
    get:
      tags:
        - line_item
      description: |
        Gets lineitems object.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    post:
      tags:
        - line_item
      description: |
        Create a new lineitem.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        201:
          description: Successful response
    
  /orders/{orderId}/line_items/{line_itemId}:
    delete:
      tags:
        - line_item
      description: |
        Gets line_item object.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: line_itemId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    put:
      tags:
        - line_item
      description: |
        Update existing new lineitem.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: line_itemId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{order_id}/address:
    post:
      tags:
        - checkout
      description: |
        input billing and shipping address
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          

  /orders/{order_id}/delivery:
    put:
      tags:
        - checkout
      description: |
        select delivery
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{order_id}/payment:
    put:
      tags:
        - checkout
      description: |
        update shipping address
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{order_id}/confirm:
    post:
      tags:
        - checkout
      description: |
        confirm the checkout
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
  
  /orders/{order_id}/complete:
    post:
      tags:
        - checkout
      description: |
        complete the checkout
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    
  /orders/{orderId}/transactions:
    get:
      tags:
        - transaction
      description: |
        Get details about an order's transactions history.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    post:
      tags:
        - transaction
      description: |
        Create a new payment.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        201:
          description: Successful response
  
  /orders/{orderId}/transactions/new:
    get:
      tags:
        - transaction
      description: |
        In order to create a new payment, you will need to know about the available payment methods.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response

  /orders/{orderId}/transactions/{transaction_id}:
    get:
      tags:
        - transaction
      description: |
        Gets transaction detail.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: transaction_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
  
  /orders/{orderId}/transactions/authorize:
    post:
      tags:
        - transaction
      description: |
        To authorize a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/capture:
    post:
      tags:
        - transaction
      description: |
        To capture a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/purchase:
    post:
      tags:
        - transaction
      description: |
        To make a purchase with a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
  
  /orders/{orderId}/transactions/void:
    post:
      tags:
        - transaction
      description: |
        To void a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/refund:
    post:
      tags:
        - transaction
      description: |
        a partial or full return of captured funds to the cardholder
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response

  /orders/clear_timeout_order:
    post:
      tags: 
        - order
      description: |
        remove all timeout order
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Successful response

definitions:
  Order:
    properties:
      id:
        type: integer
        format: int64
      shopper_id:
        type: integer
      subtotal:
        type: number
      subtotal_with_tax:
        type: number
      subtotal_without_tax:
        type: number
      shipping_fee:
        type: number
      shipping_fee_with_tax:
        type: number
      shipping_fee_without_tax:
        type: number
      discount:
        type: number
      total:
        type: number
      total_with_tax:
        type: number
      total_without_tax:
        type: number
      payment_method:
        type: string
      payment_state:
        type: string
      transactions:
        type: string
      billing_address:
        type: string
      shipping_address:
        type: string
      is_shipping_address_required:
        type: boolean
      state_id:
        type: integer
        format: int32
      state:
        type: string
      ip_address:
        type: string
      currency_code:
        type: string
      is_test:
        type: boolean
      paid_date_utc:
        type: string
        format: date-time 
  Transaction:
    properties:
      id:
        type: integer
        format: int64
      type:
        type: string
      request amount:
        type: number
      response amount:
        type: number
      status:
        type: string
      last_modified_date:
        type: string
        format: date-time
      payment_method:
        type: string
      last_4_digits:
        type: integer
        format: int32
      expiration:
        type: number
        format: int32
