swagger: '2.0'

info:
  version: "0.0.1"
  title: Payment Service API

paths:
  

          
  /orders/{orderId}/transactions:
    get:
      tags:
        - transaction
      description: |
        Get details about an order's transactions history.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    post:
      tags:
        - transaction
      description: |
        Create a new payment.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        201:
          description: Successful response
  
  /orders/{orderId}/transactions/new:
    get:
      tags:
        - transaction
      description: |
        In order to create a new payment, you will need to know about the available payment methods.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/{transaction_id}:
    get:
      tags:
        - transaction
      description: |
        Gets transaction detail.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: transaction_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
  
  /orders/{orderId}/transactions/authorize:
    post:
      tags:
        - transaction
      description: |
        To authorize a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/capture:
    post:
      tags:
        - transaction
      description: |
        To capture a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/purchase:
    post:
      tags:
        - transaction
      description: |
        To make a purchase with a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
  
  /orders/{orderId}/transactions/void:
    post:
      tags:
        - transaction
      description: |
        To void a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/refund:
    post:
      tags:
        - transaction
      description: |
        a partial or full return of captured funds to the cardholder
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
