swagger: '2.0'

info:
  version: "0.0.1"
  title: Payment Service API

paths:
  
          
          
  /payment:
    get:
      tags:
        - product
      description: |
        Gets `Products` objects.
        Optional query param of **size** determines
        size of returned array
      produces:
        - application/json
      parameters:
        - name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        200:
          description: Successful response
    post:
      tags:
        - product
      description: |
        Create a new product.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          required: false
          schema:
            $ref: "#/definitions/Product"
      responses:
        201:
          description: Successful response
        400:
          description: Invaild input
          
  /products/{productId}:
    get:
      tags:
        - product
      description: |
        Gets `Products` objects.
        Optional query param of **size** determines
        size of returned array
      parameters:
        - in: path
          name: productId
          description: Size of array
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    delete:
      tags:
        - product
      description: "Deletes a product"
      operationId: deletePet
      produces:
        - application/json
        - application/xml
      parameters:
        - name: productId
          in: path
          description: Pet id to delete
          required: true
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid product value
    post:
      description: |
        Update existing product.
      parameters:
        # An example parameter that is in query and is required
        -
          name: productId
          in: path
          description: productId
          required: true
          type: number
          format: int64
      responses:
        # Response code
        200:
          description: Successful response
  
  /products/{productId}/variations:
    get:
      tags:
        - variation
      description: |
        Gets `Variation` objects.
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    post:
      tags:
        - variation
      description: |
        Create a new variation.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: body 
          in: body
          description: Variation object that needs to be added to the product
          required: false
          schema:
            $ref: "#/definitions/Variation"
      responses:
        200:
          description: Successful response
        400:
          description: Invaild input
          
  /products/{productId}/variations/{variation_id}:
    put:
      tags:
        - variation
      description: |
        update variation object
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: variation_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    delete:
      tags:
        - variation
      description: |
        delete variation object
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: variation_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  
  /warehouses:
    get:
      tags:
        - warehouse
      description: |
        Gets `Warehouse` objects.
      produces:
        - application/json
      responses:
        200:
          description: Successful response
  
  /warehouse/{warehouseId}/stock_items:
    get:
      tags:
        - warehouse
      description: |
        Gets `stock_item` objects.
      produces:
        - application/json
      parameters:
        - name: warehouseId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders:
    get:
      description: |
        Gets `Products` objects.
        Optional query param of **size** determines
        size of returned array
      produces:
        - application/json
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfProducts
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
    post:
      tags: 
        - order
      description: |
        Create a new order.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        200:
          description: Successful response
  
  /orders/{orderId}:
    get:
      tags:
        - order
      description: |
        Gets order object.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    put:
      tags:
        - order
      description: |
        Update existing order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/close:
    post:
      tags:
        - order
      description: |
        Close the order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/open:
    post:
      tags:
        - order
      description: |
        Re-open the order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/cancel:
    post:
      tags:
        - order
      description: |
        Cancel the order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/line_items:
    get:
      tags:
        - line_item
      description: |
        Gets lineitems object.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    post:
      tags:
        - line_item
      description: |
        Create a new lineitem.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        201:
          description: Successful response
    
  /orders/{orderId}/line_items/{line_itemId}:
    delete:
      tags:
        - line_item
      description: |
        Gets line_item object.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: line_itemId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    put:
      tags:
        - line_item
      description: |
        Update existing new lineitem.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: line_itemId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions:
    get:
      tags:
        - transaction
      description: |
        Get details about an order's transactions history.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    post:
      tags:
        - transaction
      description: |
        Create a new payment.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        201:
          description: Successful response
  
  /orders/{orderId}/transactions/new:
    get:
      tags:
        - transaction
      description: |
        In order to create a new payment, you will need to know about the available payment methods.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/{transaction_id}:
    get:
      tags:
        - transaction
      description: |
        Gets transaction detail.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: transaction_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
  
  /orders/{orderId}/transactions/authorize:
    post:
      tags:
        - transaction
      description: |
        To authorize a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/capture:
    post:
      tags:
        - transaction
      description: |
        To capture a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/purchase:
    post:
      tags:
        - transaction
      description: |
        To make a purchase with a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
  
  /orders/{orderId}/transactions/void:
    post:
      tags:
        - transaction
      description: |
        To void a payment
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/transactions/refund:
    post:
      tags:
        - transaction
      description: |
        a partial or full return of captured funds to the cardholder
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /checkouts/{order_id}/:
    post:
      tags:
        - checkout
      description: |
        checkout an order
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    put:
      tags:
        - checkout
      description: |
        update the order
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /checkouts/{order_id}/address:
    post:
      tags:
        - checkout
      description: |
        input billing and shipping address
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          

  /checkouts/{order_id}/delivery:
    put:
      tags:
        - checkout
      description: |
        select delivery
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /checkouts/{order_id}/payment:
    put:
      tags:
        - checkout
      description: |
        update shipping address
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /checkouts/{order_id}/confirm:
    post:
      tags:
        - checkout
      description: |
        confirm the checkout
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
  
  /checkouts/{order_id}/complete:
    post:
      tags:
        - checkout
      description: |
        complete the checkout
      produces:
        - application/json
      parameters:
        - name: order_id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    



