swagger: '2.0'

info:
  version: "0.0.1"
  title: Pricing Service API

paths:


  /pricing:
    get:
      tags:
        - pricing
      description: |
        Get `pricing` objects.
      produces:
        - application/json
      responses:
        200:
          description: Successful response
    post:
      tags:
        - pricing
      description: |
        Create a `pricing` object.
      produces:
        - application/json
      responses:
        201:
          description: Successful response

          
  /pricing/{pricing-id}:
    get:
      tags:
        - pricing
      description: |
        To get an `pricing` object
      produces:
        - application/json
      parameters:
        - name: pricing-id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    put:
      tags:
        - pricing
      description: |
        To update an `pricing` object
      produces:
        - application/json
      parameters:
        - name: pricing-id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    delete:
      tags:
        - pricing
      description: |
        To delete an `pricing` object
      produces:
        - application/json
      parameters:
        - name: pricing-id
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: Successful response
          



 
    
definitions:
  Pricing:
    properties:
      id:
        type: integer
        format: int64
      state:
        type: string
      order-id:
        type: integer
        format: int64
      product-id:
        type: integer
        format: int64
      variation-id:
        type: integer
        format: int64

