swagger: '2.0'

info:
  version: "0.0.1"
  title: API

paths:
  /products:
    get:
      description: |
        Gets `Products` objects.
        Optional query param of **size** determines
        size of returned array
      produces:
        - application/json
      parameters:
        - name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        200:
          description: Successful response
    post:
      description: |
        Create a new product.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          required: false
          schema:
            $ref: "#/definitions/Product"
      responses:
        200:
          description: Successful response
        400:
          description: Invaild input
          
  /products/{productId}:
    get:
      description: |
        Gets `Products` objects.
        Optional query param of **size** determines
        size of returned array
      parameters:
        - in: path
          name: productId
          description: Size of array
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    delete:
      tags:
        - product
      description: "Deletes a product"
      operationId: deletePet
      produces:
        - application/json
        - application/xml
      parameters:
        - name: productId
          in: path
          description: Pet id to delete
          required: true
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid product value
    post:
      description: |
        Update existing product.
      parameters:
        # An example parameter that is in query and is required
        -
          name: productId
          in: path
          description: productId
          required: true
          type: number
          format: int64
      responses:
        # Response code
        200:
          description: Successful response
  
  /products/{productId}/variations:
    get:
      tags:
        - variation
      description: |
        Gets `Variation` objects.
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    post:
      tags:
        - variation
      description: |
        Create a new variation.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: body 
          in: body
          description: Variation object that needs to be added to the product
          required: false
          schema:
            $ref: "#/definitions/Variation"
      responses:
        200:
          description: Successful response
        400:
          description: Invaild input
  
  /warehouses:
    get:
      tags:
        - warehouse
      description: |
        Gets `Warehouse` objects.
      produces:
        - application/json
      responses:
        200:
          description: Successful response
  
  /warehouse/{warehouseId}/stock_items:
    get:
      tags:
        - warehouse
      description: |
        Gets `stock_item` objects.
      produces:
        - application/json
      parameters:
        - name: warehouseId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
  
  /orders:
    get:
      description: |
        Gets `Products` objects.
        Optional query param of **size** determines
        size of returned array
      produces:
        - application/json
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfProducts
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
    post:
      tags: 
        - order
      description: |
        Create a new order.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        200:
          description: Successful response
  
  /orders/{orderId}:
    get:
      tags:
        - order
      description: |
        Gets order object.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          
  /orders/{orderId}/line_items:
    get:
      tags:
        - line_item
      description: |
        Gets lineitems object.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    post:
      tags:
        - line_item
      description: |
        Create a new lineitem.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    
  /orders/{orderId}/line_items/{line_itemId}:
    delete:
      tags:
        - line_item
      description: |
        Gets line_item object.
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: line_itemId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    put:
      tags:
        - line_item
      description: |
        Update existing new lineitem.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
        - name: line_itemId
          in: path
          description: ""
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
    
definitions:
  Product:
    properties:
      id:
        type: integer
        format: int64
  Variation:
    properties:
      id:
        type: integer
        format: int64
